#!/usr/bin/env python3
"""Render one frame-accurate reference video per scene, named for its funscript.

    .venv/bin/python code/refvideo.py [names...]      render, skipping what is already there
    .venv/bin/python code/refvideo.py --force         re-render everything
    .venv/bin/python code/refvideo.py --check         what would be rendered; write nothing
    .venv/bin/python code/refvideo.py --verify        decode what is there and check it frame by frame

Options: --multiple=N (N video frames per sprite frame), --one-loop (a file one animation loop long
rather than as long as the scene's funscript), --scale=N (nearest-neighbour pixel scale, default 2),
--out=DIR.

The point is a video whose timing *is* the game's, so a scripter working against it hands back a
curve that needs no retiming. Everything comes out of the shipped assets - the same
`animcheck.clip_frames` call the whole measurement chain is built on - so there is no capture, no
dropped frame and no drift.

Three things this gets right that a naive dump does not:

**Frames start at k/fps, not at k*duration/n.** Those are the same number for every clip but
`GooperGrabScreenCum`, where a second sprite curve makes the animator hold the clip 1500 ms while
its own 14 frames last 1400 - so the last frame is held for the final 100 ms rather than every
frame being stretched by 7%. `animcheck.frame_times` is the function that already knows this.

**A file is as long as the scene's funscript, not one animation loop** - the loop repeated until it
reaches the row's length, cut on a frame boundary (`frame_sequence`). A scripter can then script the
whole video instead of scripting a loop and working out how many of them the row wants; the loop
length is still in the sidecar and the table, since that is what a curve aligns to. `--one-loop`
renders a single loop instead.

**The video runs at the clip's own sample rate** (6, 8, 9 or 10 fps across this set), so one sprite
is exactly one video frame: nothing is duplicated, nothing is dropped, and frame k of the file is
frame k of the game. `--multiple N` emits N identical frames per sprite for players that handle a
6 fps file badly; it is still an integer multiple, so the property holds.

**Frames are registered by `textureRectOffset`, not bottom-left aligned.** Sprites are alpha
trimmed to different sizes per frame, and where the trim came off differs per frame too: the six
`GhoulGrabStart` frames lose 9-16 px from their left edge. The measurement tools paste against a
shared bottom-left corner, which is fine for a proxy and wrong for a picture - it would put a 7 px
horizontal jitter on screen that the game does not have. Unity keeps the trimmed rect's offset
inside the full sprite cell in `m_RD.textureRectOffset`, and the cell is placed by `m_Pivot`, so
the exact in-game registration is readable. That is what this uses.

Scenes come from `animsweep.MAP`, i.e. every row that answers to an animation. Two kinds of row are
skipped, and both are named on the way out rather than silently absent:

  ladder rows      the seven `filler` tiers and the serpent's three hypnosis tiers, generated by
                   `code/ladders.py` against each other rather than against any scene
  unmapped rows    `ambient_wendigo_hole`, whose "diorama" turned out to be the wendigo peephole's
                   ambient audio object - the scene itself is `peek_wendigo_ride`, which does get a
                   video (learnings/game-scenes.md, code/TIMING-AUDIT.md)

Output lands in `Edi/_reference/videos/` (untracked, regenerable): `<row>.mp4` beside `<row>.json`
with the true period in it, plus `index.csv` and a `README.md` for whoever is handed the folder.
"""
import csv, json, os, shutil, subprocess, sys

import animcheck as A
import animsweep as S
import ladders as L
import pncpaths as P

ROOT = P.ROOT
OUTDIR = os.path.join(ROOT, "Edi/_reference/videos")
BG = (20, 20, 24)
SCALE = 2


def sprite_layout(sprites):
    """(canvas w, h, [(x, y) per frame]) - exact in-game registration.

    A sprite's on-screen extent is its full `m_Rect` cell, anchored at `m_Pivot`; the pixels UnityPy
    hands back are the alpha-trimmed sub-rect, whose corner inside that cell is
    `m_RD.textureRectOffset`. Working in pivot-relative coordinates (Unity's y counts up from the
    cell's bottom-left) makes frames comparable even if a clip mixes cells of different sizes, which
    a clip drawing from two atlas pages can. The canvas is the union of the cells, so the framing is
    what the game reserves rather than a crop that breathes with the trim.
    """
    boxes = []
    for s in sprites:
        t = s.read_typetree()
        rect, rd = t["m_Rect"], t["m_RD"]
        piv = t.get("m_Pivot") or {"x": 0.5, "y": 0.5}
        px, py = piv["x"] * rect["width"], piv["y"] * rect["height"]
        off = rd.get("textureRectOffset") or {"x": 0.0, "y": 0.0}
        w, h = s.read().image.size
        boxes.append(dict(cell=(-px, rect["width"] - px, -py, rect["height"] - py),
                          img=(off["x"] - px, off["y"] - py, w, h)))
    L = min(b["cell"][0] for b in boxes); R = max(b["cell"][1] for b in boxes)
    B = min(b["cell"][2] for b in boxes); T = max(b["cell"][3] for b in boxes)
    W, H = int(round(R - L)), int(round(T - B))
    pos = []
    for b in boxes:
        x, y, w, h = b["img"]
        pos.append((int(round(x - L)), int(round(T - (y + h)))))     # PIL y counts down
    return W, H, pos


def compose(sprites, scale=SCALE):
    """The clip's frames as one list of equal-sized RGB images, ready to hand to ffmpeg."""
    from PIL import Image
    W, H, pos = sprite_layout(sprites)
    out = []
    for s, (x, y) in zip(sprites, pos):
        im = s.read().image.convert("RGBA")
        canvas = Image.new("RGBA", (W, H), BG + (255,))
        canvas.alpha_composite(im, (x, y))
        rgb = canvas.convert("RGB")
        if scale != 1:
            rgb = rgb.resize((W * scale, H * scale), Image.NEAREST)
        out.append(rgb)
    return out


def motion_track(sprites, scale=1):
    """Screen-space centroid of whatever moves, per frame. What a multi-axis scripter needs first.

    The existing proxies answer "how deep", i.e. one number for the stroke axis. A scripter writing
    surge/sway/twist needs the other question answered too: *does anything in this scene move
    sideways, and when*. That is readable here and nowhere else in the toolchain, because it is only
    meaningful once frames are registered exactly - a bottom-left stack puts up to 16 px of trim
    jitter on the horizontal axis, which is the same order as the motion being looked for.

    Method is `proxies.moving_mass`, in two dimensions: take the median frame as the plate, threshold
    the residual, and return the centroid of what is left. y counts up from the bottom of the canvas,
    so both series read the way the screen does.

    Screen space is not device space. A horizontal travel is sway on one camera angle and surge on
    another, and a rotation shows up as neither; deciding which axis a scene wants is the scripter's
    call, and this only says where the motion is.
    """
    import numpy as np
    from PIL import Image
    W, H, pos = sprite_layout(sprites)
    stack = np.zeros((len(sprites), H, W, 3), np.float32)
    for k, (sp, (x, y)) in enumerate(zip(sprites, pos)):
        im = sp.read().image.convert("RGBA")
        canvas = Image.new("RGBA", (W, H), (0, 0, 0, 255))
        canvas.alpha_composite(im, (x, y))
        stack[k] = np.asarray(canvas.convert("RGB"), np.float32)
    d = np.abs(stack - np.median(stack, axis=0)).mean(axis=3)
    thr = max(6.0, float(np.percentile(d, 99.0)) * 0.25)
    xs, ys = [], []
    for k in range(len(sprites)):
        yy, xx = np.nonzero(d[k] > thr)
        if len(xx) < 20:                       # nothing moved in this frame; hold the last centroid
            xs.append(xs[-1] if xs else None); ys.append(ys[-1] if ys else None); continue
        xs.append(float(xx.mean())); ys.append(float(H - yy.mean()))
    if all(v is None for v in xs):
        return None
    fill = next(v for v in xs if v is not None)
    xs = [fill if v is None else v for v in xs]
    fill = next(v for v in ys if v is not None)
    ys = [fill if v is None else v for v in ys]

    def norm(v):
        lo, hi = min(v), max(v)
        return [round((x - lo) / (hi - lo) * 100.0, 1) for x in v] if hi - lo > 1e-6 else [0.0] * len(v)

    return dict(canvas_px=[W, H], threshold=round(thr, 2),
                centroid_x_px=[round(v, 2) for v in xs], centroid_y_px=[round(v, 2) for v in ys],
                travel_x_px=round(max(xs) - min(xs), 2), travel_y_px=round(max(ys) - min(ys), 2),
                centroid_x_0_100=norm(xs), centroid_y_0_100=norm(ys),
                note=("screen-space centroid of the residual against the median frame, one entry per "
                      "sprite frame, y counting up. Travel is in source pixels before --scale. Which "
                      "device axis a travel belongs to depends on the camera and is not decided here."))


def _even(im):
    """h264 with yuv420p needs both dimensions even; pad rather than resample."""
    from PIL import Image
    w, h = im.size
    if w % 2 == 0 and h % 2 == 0:
        return im
    p = Image.new("RGB", (w + w % 2, h + h % 2), BG)
    p.paste(im, (0, 0))
    return p


def encode(frames, fps, path):
    """Write the frames as an all-intra h264 file at `fps`.

    `-g 1` makes every frame a keyframe: the files are seconds long and a few hundred KB, and a
    scripter stepping frame by frame in a player gets the exact frame rather than the last I-frame
    plus a guess."""
    W, H = frames[0].size
    cmd = ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
           "-f", "rawvideo", "-pixel_format", "rgb24", "-video_size", f"{W}x{H}",
           "-framerate", str(fps), "-i", "-",
           "-c:v", "libx264", "-preset", "veryslow", "-crf", "14", "-g", "1",
           "-pix_fmt", "yuv420p", "-movflags", "+faststart", "-r", str(fps), path]
    p = subprocess.Popen(cmd, stdin=subprocess.PIPE)
    for f in frames:
        p.stdin.write(f.tobytes())
    p.stdin.close()
    if p.wait() != 0:
        sys.exit(f"refvideo: ffmpeg failed on {path}")


def verify(pl, path, multiple, video_ms, scale):
    """Decode the file back and prove every video frame is the sprite frame it should be.

    A frame-accurate claim nothing checks is a claim. This re-composes the clip, decodes the mp4,
    and for each decoded frame asks which source frame it is *closest* to - not merely whether it
    is close to the expected one, which would pass a file whose frames were all identical. Codec
    noise at crf 14 is a mean absolute difference under ~1 of 255; a wrong frame scores in the
    tens.

    "Closest" has to allow ties, because **15 of the 93 clips list a pixel-identical sprite twice** -
    `DragonFaceSit` opens with `face_sit-Sheet_0` on two consecutive keyframes, `Gravy_Cum` repeats
    `BJ cum-Sheet_2_2` five frames later, and `Zombie_Cum` ends on a held frame. No decoder can tell
    those apart and nothing is wrong with the file, so the test is that the expected frame is *among*
    the closest, not that it is uniquely so.
    """
    import numpy as np
    src = [_even(im) for im in compose(pl["sprites"], scale)]
    W, H = src[0].size
    raw = subprocess.run(["ffmpeg", "-v", "error", "-i", path, "-f", "rawvideo",
                          "-pix_fmt", "rgb24", "-"], capture_output=True).stdout
    dec = np.frombuffer(raw, np.uint8).reshape(-1, H, W, 3).astype(np.int16)
    want = [k for k in frame_sequence(pl, video_ms) for _ in range(multiple)]
    if dec.shape[0] != len(want):
        return f"{dec.shape[0]} frames in the file, {len(want)} expected"
    arr = [np.asarray(im, np.int16) for im in src]
    worst = 0.0
    for i, k in enumerate(want):
        mad = [float(np.abs(a - dec[i]).mean()) for a in arr]
        if mad[k] > min(mad) + 1.0:
            return f"video frame {i} is sprite frame {int(np.argmin(mad))}, expected {k}"
        worst = max(worst, mad[k])
    return None if worst < 5.0 else f"codec error {worst:.1f} is too high"


def definitions():
    """{row name: (start ms, end ms, loop)} out of the gallery table."""
    out = {}
    for r in P.definitions_rows():
        out[r["Name"]] = (int(r["StartTime"]), int(r["EndTime"]), r["Loop"].strip().lower() == "true")
    return out


def frame_sequence(pl, script_len):
    """Which sprite frame each video slot shows, for a file `script_len` ms long.

    A scene's video is as long as the funscript that plays over it, not one loop of the animation:
    a scripter opening it should be able to script the whole file rather than script a loop and then
    work out how many of them the row wants. The loop is still the unit - the sequence is the clip's
    own slots repeated - and `loop_ms` in the sidecar and the table is still the number to align to.

    A loop's slots are its frames plus any the animator holds past them (only `GooperGrabScreenCum`
    has one). The cut is at `round(ms * fps / 1000)`: 36 of the 93 rows have a script length that is
    a whole number of frames only after rounding, because a 9 fps frame is 111.1 ms and the lengths
    are stored in whole ms. The rounding is under 0.005 of a frame in every case."""
    per_loop = list(range(pl["frames"])) + [pl["frames"] - 1] * (pl["slots"] - pl["frames"])
    total = max(1, int(round(script_len * pl["fps"] / 1000.0)))
    reps = -(-total // len(per_loop))
    return (per_loop * reps)[:total]


def plan(env, name, clip, defs):
    """Everything about one scene that does not depend on having rendered it yet."""
    sprites, dur, fps = A.clip_frames(env, clip)
    stem = name.lower()
    script = os.path.join("Edi/Gallery/handy2pro", stem + ".funscript")
    if not sprites:
        return dict(name=name, clip=clip, error="clip not found or has no sprite frames")
    if not os.path.exists(os.path.join(ROOT, script)):
        return dict(name=name, clip=clip, error=f"no funscript at {script}")
    n = len(sprites)
    # The animator holds the clip for m_StopTime whatever its own frames last; slots past the last
    # sprite are that sprite held. Only GooperGrabScreenCum has any (14 frames in 15 slots).
    slots = max(n, int(round(dur * fps / 1000.0)))
    d = defs.get(name)
    script_ms = float(d[1] - d[0]) if d else dur
    return dict(name=name, clip=clip, script=script, sprites=sprites, frames=n, slots=slots,
                loop_ms=dur, fps=fps, frame_times=A.frame_times(n, dur, fps),
                script_ms=script_ms)


def render(pl, outdir, multiple, video_ms, scale):
    imgs = [_even(im) for im in compose(pl["sprites"], scale)]
    seq = [imgs[k] for k in frame_sequence(pl, video_ms)]
    frames = [im for im in seq for _ in range(multiple)]
    path = os.path.join(outdir, pl["name"].lower() + ".mp4")
    encode(frames, int(round(pl["fps"] * multiple)), path)
    return path, len(frames)


def sidecar(pl, defs, video_fps, video_frames, video_ms, scale, path):
    d = defs.get(pl["name"])
    period, reps = A.stroke_period(pl["sprites"], pl["loop_ms"])
    track = motion_track(pl["sprites"])
    doc = {
        "row": pl["name"],
        "funscript": pl["script"],
        "clip": pl["clip"],
        "loop_ms": round(pl["loop_ms"], 3),
        "stroke_period_ms": round(period, 3),
        "strokes_per_loop": reps,
        "sprite_frames": pl["frames"],
        "sample_rate_fps": pl["fps"],
        "frame_times_ms": [round(t, 3) for t in pl["frame_times"]],
        "held_tail_frames": pl["slots"] - pl["frames"],
        "video_fps": video_fps,
        "video_frames": video_frames,
        "video_ms": round(video_ms, 1),
        "script_ms": round(pl["script_ms"], 1),
        "loops_in_file": round(video_ms / pl["loop_ms"], 3),
        "pixel_scale": scale,
        "definitions_row": None if not d else {"StartTime": d[0], "EndTime": d[1], "Loop": d[2]},
        "motion": track,
        "note": ("frame k is on screen at frame_times_ms[k]; the file runs at the clip's own sample "
                 "rate, so video frame k*(video_fps/sample_rate_fps) is sprite frame k. loop_ms is "
                 "how long the animator holds the clip, which is the length to align a loop to - "
                 "not sprite_frames/sample_rate_fps, which is shorter when held_tail_frames > 0."),
    }
    json.dump(doc, open(path, "w", encoding="utf-8"), indent=2)
    return doc


def readme_text(rows):
    """The page a scripter who has never seen this project reads first.

    They want to know what the files are, what to name what they write, and how long a loop is.
    Everything that is a fact about *this repo* - row names, ladders, sprite registration, which
    tool made the folder - is noise to them, so it is not here; the numbers they need are in a
    table on the page rather than in a CSV they have to open. `code/README.md` and
    `learnings/edi-integration.md` are where the project-side story stays.
    """
    top = sorted((r for r in rows if r["travel_x_px"] != ""),
                 key=lambda r: -float(r["travel_x_px"]))[:5]
    tbl = "\n".join(
        f"| `{r['row'].lower()}` | {r['script_ms']} ms | {r['loop_ms']:.0f} ms | "
        f"{r['sample_rate_fps']} | {r['sprite_frames']} | {r['strokes_per_loop']} | "
        f"{('%.0f' % float(r['travel_x_px'])) if r['travel_x_px'] != '' else '-'} |"
        for r in sorted(rows, key=lambda r: r["row"].lower()))
    return f"""# Scene reference videos — Post Nut Calamity

Every video here is one scene from the game, drawn from the game's own artwork rather than screen
recorded. **The timing is exact**: the video plays at the same frame rate as the game's animation,
and each file is exactly as long as that scene's script should be. Script the video from start to
end and it lines up in the game with nothing to adjust.

## Scripting one

1. Open a scene's `.mp4` in whatever you script with.
2. **Script the whole video.** Each file is already exactly as long as that scene's script needs to
   be, so you do not have to work out any lengths. Give the last action the same position as the
   first, so it does not jump where it repeats.
3. Save it as the video's name with a `.funscript` extension: `gravy_start.mp4` becomes
   `gravy_start.funscript`. That name is how the game finds it — nothing else to fill in.
4. Positions are the usual 0-100. In this project's existing scripts **0 is deep**.

Every scene already has a single-axis script, so you can see what has been done. It sits in the
mod's gallery under the same name: `Edi/Gallery/handy2pro/<name>.funscript`.

## Extra axes

An extra axis is just another file with the axis in the name, next to the first one:

    gravy_start.funscript          the stroke
    gravy_start.twist.funscript    the same scene's twist
    gravy_start.roll.funscript     ... and roll

Nothing else changes: no list to update, no settings, no code. Usable axis names are `surge`,
`sway`, `twist`, `roll`, `pitch`, `vibrate`, `valve`, `suction` — plus `frequency`, `volume` and
`pulseWidth` for e-stim gear.

Three things to know:

* **Every axis of a scene must be the same length** — the video's length, the **length** column. A
  shorter axis file does not loop on its own; it plays and then holds its last position while the
  rest of the scene keeps going.
* **An axis you do not write rests in the middle (50), not at 0** — except `vibrate`, which rests
  at 0. So write only the axes that actually move.
* **Do not put a dot in a filename for any other reason.** A dot is how the axis is read.

## Reading the table

* **length** — the video's length, and so the length your script should be.
* **loop** — how long one repeat of the animation is. The video is that loop repeated up to the
  length above, so a motion you place at 0 ms belongs again one loop later.
* **fps / frames** — the animation's own frame rate, and how many frames one loop has. The video has
  exactly those frames, so stepping one video frame steps one animation frame.
* **strokes** — how many identical strokes are inside one loop. `2` means the loop already repeats
  the same motion twice.
* **sideways** — how far the moving part travels left-to-right across the screen in one loop, in
  pixels. It is a hint for whether a scene has anything worth a second axis: a big number means
  visible sideways motion, a number near zero means there is none to follow. It does **not** say
  which axis — whether sideways on screen is sway, surge or a twist depends on the camera angle in
  that scene, and that call is yours.

Most sideways motion, if you are looking for somewhere to start:
{chr(10).join('* `' + r['row'].lower() + '` — ' + ('%.0f' % float(r['travel_x_px'])) + ' px' for r in top)}

## The scenes

| scene | length | loop | fps | frames | strokes | sideways |
|---|---|---|---|---|---|---|
{tbl}

## If you script with tools

`index.csv` is the table above as a spreadsheet, and each `<name>.json` holds the same numbers for
one scene plus the exact millisecond each frame appears. Nothing needs them; ignore them if they
are not useful to you.
"""




def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = [a for a in sys.argv[1:] if a.startswith("--")]
    if "--help" in flags or "-h" in flags:
        print(__doc__); return 0

    def opt(nm, dflt, cast=int):
        for f in flags:
            if f.startswith(nm + "="):
                return cast(f.split("=", 1)[1])
        return dflt

    check = "--check" in flags
    verifying = "--verify" in flags
    force = "--force" in flags
    multiple = opt("--multiple", 1)
    one_loop = "--one-loop" in flags
    scale = opt("--scale", SCALE)
    outdir = opt("--out", OUTDIR, str)
    if multiple < 1 or scale < 1:
        sys.exit("refvideo: --multiple and --scale are >= 1")
    if not check and not shutil.which("ffmpeg"):
        sys.exit("refvideo: ffmpeg not on PATH")

    wanted = [n for n in S.MAP if not args or n in args or n.lower() in [a.lower() for a in args]]
    unknown = [a for a in args if a not in S.MAP and a.lower() not in [n.lower() for n in S.MAP]]
    if unknown:
        sys.exit(f"refvideo: not a scene in animsweep.MAP: {', '.join(unknown)}")

    defs = definitions()
    ladder = {n for n, _, _ in L.FILLER_ROWS} | {n for n, _ in L.HYPNOSIS_ROWS}
    skipped = sorted(n for n in defs if n not in S.MAP)
    orphan = [n for n in skipped if n not in ladder]

    env = A.load_env()
    if not check:
        os.makedirs(outdir, exist_ok=True)
    rows, bad = [], []
    print(f"{'row':<30}{'clip':<38}{'frames':>7}{'fps':>5}{'loop ms':>9}{'stroke':>9}{'x':>3}")
    for name in wanted:
        pl = plan(env, name, S.MAP[name], defs)
        if pl.get("error"):
            bad.append((name, pl["error"])); print(f"{name:<30}{pl['clip']:<38}  -- {pl['error']}"); continue
        vfps = int(round(pl["fps"] * multiple))
        video_ms = pl["loop_ms"] if one_loop else pl["script_ms"]
        vpath = os.path.join(outdir, name.lower() + ".mp4")
        jpath = os.path.join(outdir, name.lower() + ".json")
        track = None
        if verifying:
            if not os.path.exists(vpath):
                bad.append((name, "not rendered")); print(f"{name:<30}{pl['clip']:<38}  -- not rendered"); continue
            err = verify(pl, vpath, multiple, video_ms, scale)
            if err:
                bad.append((name, err))
            period, reps = A.stroke_period(pl["sprites"], pl["loop_ms"])
            state = err or "verified"
        elif check or (os.path.exists(vpath) and not force):
            period, reps = A.stroke_period(pl["sprites"], pl["loop_ms"])
            if os.path.exists(jpath):
                track = json.load(open(jpath, encoding="utf-8")).get("motion")
            state = "up to date" if (not check and os.path.exists(vpath)) else ""
        else:
            _, nvid = render(pl, outdir, multiple, video_ms, scale)
            doc = sidecar(pl, defs, vfps, nvid, video_ms, scale, jpath)
            period, reps, track = doc["stroke_period_ms"], doc["strokes_per_loop"], doc["motion"]
            state = f"{os.path.getsize(vpath)/1024:.0f}K"
        print(f"{name:<30}{pl['clip']:<38}{pl['frames']:>7}{pl['fps']:>5.0f}"
              f"{pl['loop_ms']:>9.1f}{period:>9.1f}{reps:>3}  {state}")
        rows.append(dict(row=name, video=name.lower() + ".mp4",
                         funscript=os.path.basename(pl["script"]), clip=pl["clip"],
                         sprite_frames=pl["frames"], sample_rate_fps=int(pl["fps"]),
                         loop_ms=round(pl["loop_ms"], 1), stroke_period_ms=round(period, 1),
                         strokes_per_loop=reps, video_fps=vfps,
                         script_ms=(defs[name][1] - defs[name][0]) if name in defs else "",
                         travel_x_px=track["travel_x_px"] if track else "",
                         travel_y_px=track["travel_y_px"] if track else ""))

    print(f"\n{len(rows)} scene(s) of {len(defs)} gallery rows.")
    print(f"  {len(ladder & set(skipped))} ladder row(s), generated against each other and not against a "
          f"scene: {', '.join(sorted(ladder & set(skipped)))}")
    if orphan:
        print(f"  {len(orphan)} row(s) with no clip mapped in animsweep.MAP: {', '.join(orphan)}")
    if bad:
        for n, e in bad:
            print(f"  MISSING {n}: {e}")
    if check or verifying:
        return 1 if bad else 0

    if args:
        print("partial run: index.csv and README.md left alone (they describe the whole set)")
        return 1 if bad else 0

    with open(os.path.join(outdir, "index.csv"), "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    open(os.path.join(outdir, "README.md"), "w",
         encoding="utf-8").write(readme_text(rows))
    print(f"wrote {outdir}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
